import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import cx from "classnames";
import { SessionProvider } from "next-auth/react";
import { Suspense } from "react";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cx(inter.className, "bg-main-page")}>
        <main>
          <div className="mr-24 ml-24 mt-3">
            <NavBar />
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
