import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import cx from "classnames";
import { SessionProvider } from "next-auth/react";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cx(inter.className, "bg-black")}>
        <main>{children}</main>
      </body>
    </html>
  );
}
